name: Mirror to Framagit
on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to framagit (HTTPS with token)
        env:
          FRAMAGIT_URL: https://framagit.org/my-privacy-dns/matrix.git
          FRAMAGIT_TOKEN: ${{ secrets.FRAMAGIT_TOKEN }}
        run: |
          printf "machine framagit.org login %s password %s\n" "spirille" "$FRAMAGIT_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
          git remote remove framagit || true
          git remote add framagit https://framagit.org/my-privacy-dns/matrix.git
          git push --prune --mirror framagit
