name: Mirror to Framagit

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to framagit (HTTPS with token via netrc)
        env:
          FRAMAGIT_URL: https://framagit.org/my-privacy-dns/matrix.git
          FRAMAGIT_TOKEN: ${{ secrets.FRAMAGIT_SSH }}
        run: |
          set -euo pipefail

          if [ -z "${FRAMAGIT_TOKEN:-}" ]; then
            echo "ERROR: FRAMAGIT_SSH (used as FRAMAGIT_TOKEN) is not set." >&2
            exit 1
          fi

          echo "Configuring ~/.netrc for framagit.org"
          printf "machine framagit.org login %s password %s\n" "spirille" "${FRAMAGIT_TOKEN}" > "$HOME/.netrc"
          chmod 600 "$HOME/.netrc"

          echo "Ensuring framagit remote points to $FRAMAGIT_URL"
          git remote remove framagit || true
          git remote add framagit "$FRAMAGIT_URL"

          echo "Remote list:"
          git remote -v

          echo "Performing dry-run push (no changes made)"
          git push --prune --mirror framagit --dry-run

          echo "Performing actual mirror push"
          git push --prune --mirror framagit
