- name: Mirror to framagit (HTTPS with token via netrc)
  env:
    FRAMAGIT_URL: https://framagit.org/my-privacy-dns/matrix.git
    FRAMAGIT_TOKEN: ${{ secrets.FRAMAGIT_SSH }}
  run: |
    set -euo pipefail
    if [ -z "${FRAMAGIT_SSH:-}" ]; then
      echo "FRAMAGIT_SSH is not set" >&2
      exit 1
    fi

    # Configure .netrc for framagit.org (no protocol prefix)
    printf "machine framagit.org login %s password %s\n" "spirille" "${FRAMAGIT_SSH}" > "$HOME/.netrc"
    chmod 600 "$HOME/.netrc"

    # Ensure remote configured to canonical HTTPS URL (no creds in URL)
    git remote remove framagit || true
    git remote add framagit "$FRAMAGIT_URL"

    # Optional: verify remote URL
    git remote -v

    # Dry-run first (optional)
    git push --prune --mirror framagit --dry-run

    # Actual push
    git push --prune --mirror framagit
