name: Sort datasets
on:
  push:
  pull_request:

env:
  GIT_NAME: '${{ secrets.GIT_NAME }}'
  GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

jobs:
  scheduler:
    name: Trigger action
    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.13'
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@main # Yet another american...
        name: Clone repository
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Install My Privacy DNS python module
        run: |
          pip install --no-cache-dir -r "${{ github.workspace }}/requirements.txt"

      - name: 'Sort our lists for doublets and order by alphabet'
        run: bash "${{ github.workspace }}/tools/sort_lists.sh"

      - name: Git Status
        run: git status

      - name: Commit changes
        continue-on-error: true
        run: |
          tag=$(date +'day: %j of year %Y %H:%M:%S')
          git config --local user.email "$GIT_EMAIL"
          git config --local user.name "$GIT_NAME"
          git commit -a -m "Committed new lists $tag"
          git pull --rebase

      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

#      - name: Commit all changed files back to the repository
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: Sorted the lists
