name: Sort CSV Files

on:
  push:
    paths:
      - 'source/**'
      - 'tools/sort_lists.py'

jobs:
  sort-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check for changes in source folder
        id: changed_files
        run: |
          changed_files=$(git diff --name-only HEAD HEAD~1 | grep -E '^source/')
          echo "::set-output name=changed_files::$changed_files"
      - name: Sort CSV files
        if: ${{ steps.changed_files.outputs.changed_files }}
        run: |
          python tools/sort_lists.py
      - name: Commit changes
        if: ${{ steps.changed_files.outputs.changed_files }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add source/
          git commit -m "Sort CSV files" -a
          git push
